version: '3'

#定義服務
services:
    #nginx
    nginx:
        build: ./nginx
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
        container_name: nginx
        restart: always
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/cert:/etc/nginx/cert
            - ./www:/usr/share/nginx/html
        networks:
            - frontend
    #php
    php:
        build: ./php
        container_name: php
        restart: always
        volumes:
            - ./www:/var/www/html
            - ./php/config/php.ini:/usr/local/etc/php/php.ini
            - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
        networks:
            - frontend
networks:
    backend:
    frontend:
