version: '3'

#定義服務
services:
    #nginx
    nginx:
        build: ./nginx
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
        container_name: nginx
        restart: always
    #php
    php:
        build: ./php
        container_name: php
        restart: always
